### ISSUE TITLE
Error when build for macOS: Receiver type 'SDLOpenGLContext' for instance message is a forward declaration

### ISSUE THREAD

**Issue by wumo** [nativium/nativium-game#5]
When running the following command on macos
```
python nativium.py target macos setup
```
Error : Receiver type 'SDLOpenGLContext' for instance message is a forward declaration

**Comment by paulocoutinhox** [comment]
Hi,

Try this branch please:
https://github.com/nativium/nativium-game/tree/new-architecture

This is working.

**Comment by wumo** [comment]
> 

ok. I'll try.

**Comment by wumo** [comment]
It's working. I'll close this issue.
